version: "3.9"

services:

  # =========================
  # PostgreSQL Database
  # =========================
  postgres:
    image: postgres:15
    container_name: garage_postgres
    restart: always
    environment:
      POSTGRES_DB: garage_manager
      POSTGRES_USER: gm_user
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # =========================
  # Spring Boot Backend
  # =========================
  backend:
    image: garage-backend:latest   # Ton image Docker Spring Boot
    container_name: garage_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/garage_manager
      SPRING_DATASOURCE_USERNAME: gm_user
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_PROFILES_ACTIVE: pfv
    ports:
      - "8090:8090"

  # =========================
  # Angular Frontend
  # =========================
    #frontend:
      #  build:
    #   context: ./frontend   # dossier contenant ton Dockerfile Angular
    # container_name: garage_frontend
      # depends_on:
    #   - backend
      #ports:
    #   - "80:80"

volumes:
  pgdata:
